# Numpy
## Agenda:
* Introduction to Numpy.
* Array Creation Routines.
* Examples.
* Array Creation from Existing Data
* Examples.

## Introduction to Numpy:
* It is a Fast Mathematical Computational Library.
* Implemented using C. 
* Dealts with homogenous data structures.
* Specialized for doing mathematical computations on high dimensional data. 
* It provides inbuilt utilities which are mutable in nature.
* As mentiond above it is using C internally, so it is fast in nature when it 
   compared to general purpose library using list available in Python.
 
## Array creation routines:
Arrays in numpy can be created in multiple ways. Let's see them one by one.

Array creation routines:
* Using Empty.
* Using Eye.
* Using One init.
* Using Zero init.
* From default value initialization(Full init)
* Using Range.
* Using Linspace
* Using Random.


Import Numpy Library as np using below statement.

In [341]:
# to import numpy lib
import numpy as np

### Using Empty:

#### empty:
* Return a new array of given shape and type, without initializing/arbitrary entries.

In [342]:
#creates array with shape (2,2) and arbitraryvalues.
np.empty(shape=(2, 2))

array([[  1.16962778e-311,   1.97626258e-323],
       [  1.58101007e-322,   3.95252517e-323]])

In [343]:
# providing dtype information along with shape
np.empty(shape=(2, 2), dtype=int)

array([[         0, 1072693248],
       [         0, 1072693248]])

#### empty_like:
* Return a new array with the same shape and type as a given array.

In [344]:
#creats array with size of a with arbitrary data
a = ([1,2,3], [4,5,6]) 
np.empty_like(a)

array([[    160512,  150994944, 1346968186],
       [1681995382, 1936028260, 1936273011]])

* we got the new array empty_array_copy with size of (a) but contents are arbitrary.

### Using Eye:

#### eye:
* Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [349]:
#creates a array and diagonals elements are initialized to 1.
np.eye(N=3,M=2,k=0,dtype=int)

array([[1, 0],
       [0, 1],
       [0, 0]])

* Here, <br />
N = Number of rows <br />
M = Nuber of columns <br />
k = Index of the diagonal(positive value refers to an upper diagonal, and a negative value to a lower diagonal.)

In [348]:
# Since k=-1 lower diagonal elements are initialized to 1
np.eye(N=3,k=-1)

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

### Using One Init:

#### ones:
* Initializes all values in array to 1.

In [352]:
#creating array with size 5
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [350]:
#creating nd array
np.ones(shape=(2,2,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

#### ones_like:
* creates new data structure with same dimension/size.

In [351]:
#Creating new array using shape of existing array
np.ones_like(ones_array3D)

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

### Using Zero init:

#### zeros:
* Creates numpy array of given size and initialize values to zero.

In [353]:
#creating array with size 5
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [354]:
#creating nd array
np.zeros(shape=(2,2,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

#### zeros_like:

* same as mention before creates a new array with same dimention.

In [355]:
#Creating new array using shape of existing array
np.zeros_like(zeros_array3D)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

### From default value initialization(Full init):

#### full:
* It initializes all the values in array to given value.

In [356]:
#Creates array of given size and initializes values to given fill_value
np.full(shape=(6,6),fill_value=99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [313]:
#Creates a new array of given size and initializes values with string hello
np.full(shape=(3,2),fill_value='hello')

array([['hello', 'hello'],
       ['hello', 'hello'],
       ['hello', 'hello']],
      dtype='<U5')

#### full_like:
* creates new array with shape of given array and fill value.

In [312]:
#creates a new array using given array size and initializes values to given fill value hello
np.full_like(array_d,'hello')

array([['hello', 'hello'],
       ['hello', 'hello'],
       ['hello', 'hello']],
      dtype='<U5')

* Just remember we need to pass both array and fill_value to full_like function.

### Using Range:

* It returns evenly spaced values within the given interval.

In [311]:
# creates a array with values between given start(10) and stop(20)(excludes) with given step size(2).
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

* In above Example params are (start=10,stop=20,step=2)
* Here, we can see that it included start value(10) but excluded stop value 20 and returned values with step size 2.
* So, remember it always generates values within the half-open interval [start, stop).

In [358]:
# creates a array with values between given start(15) and stop(10)(excludes) with given step size(-1).
np.arange(15,10,-1)

array([15, 14, 13, 12, 11])

* arange function also works with negative and non-integer(eg:0.1) step size.
* But for non-integer the results will often not be consistent.
* It is better to use linspace for non integer step cases.

### Using Linspace:

* It is also returns evenly spaced values  withing given interval like range function.
* But unlike range function it includes both start and stop values by default(eg: [start,stop]).
* optionally we can exclude stop value from interval(eg: [start,stop)).


In [359]:
#creates array which size equal to given num value(5) and places values between start(2.0) and stop(3.0)
np.linspace(2.0, 3.0, num=5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

* Here, linspace returned 5 evenly spaced values within interval [start=2.0,stop=3.0].

In [360]:
#creates array which size equal to given num value(5) and places values between start(2.0) and stop(3.0)(excludes)
np.linspace(2.0,3.0,num=5,endpoint=False)

array([ 2. ,  2.2,  2.4,  2.6,  2.8])

* If the endpoint is False it returns values within interval [start=2.0,stop=3.0)

### Using Random:
* Creates a array with given shape and populate it with random values.

#### rand:
* Populates random values within interval [0,1).
* In statistical terms it returns random samples from a uniform distribution over [0, 1).

In [361]:
#creates array with size equal to given integer and initializes values to random values between [0,1)
np.random.rand(10)

array([ 0.55033135,  0.95035711,  0.89764106,  0.34027365,  0.44794192,
        0.45594277,  0.4485773 ,  0.98394663,  0.72660416,  0.26183921])

In [306]:
#creates array of given size and initialize values to random values between[0,1)
np.random.rand(3,2)

array([[ 0.69055771,  0.18017498],
       [ 0.50338971,  0.07918502],
       [ 0.90105452,  0.49737752]])

#### randn:
* It fills sample values from the “standard normal” distribution.
* standard normal distribution means mean is equal to 0 and variance is equal to 1.

In [305]:
#creates array and values are initialized in standard normal distribution.
np.random.randn(2,4)

array([[ 2.20060746,  0.37324182,  0.73642848, -0.96839575],
       [-0.32664876,  1.78067469, -0.04714109, -0.99208077]])

* randn function returns a single float randomly sampled from the distribution is returned if no argument is provided.
* see the example below.

In [304]:
#return a random value.
np.random.randn()

-0.554174466044771

#### randint:
* randint return random integers from low (inclusive) to high (exclusive).
* size and  high value is optional.
* in statistical terms return random integers from the “discrete uniform” distribution. 

In [362]:
#creates array with given size (3,3) and values are initialized to random values between low(5) and high(10)
np.random.randint(low=5,high=10,size=(3,3))

array([[6, 7, 6],
       [7, 8, 9],
       [8, 7, 7]])

In [364]:
#return an integer less than given low(5)
np.random.randint(low=5)

3

In [365]:
#creates an array  with given size(10) and values are initialized to random values less than low(5)
np.random.randint(low=5,size=10)

array([3, 0, 0, 1, 2, 1, 2, 4, 3, 4])