# Numpy
## Agenda:
* Introduction to Numpy.
* Array Creation Routines with Examples.
* Array Creation from Existing Data with Examples.

## Introduction to Numpy:
* It is a Fast Mathematical Computational Library.
* Implemented using C. 
* Dealts with Homogenous Data Structures.
* Specialized for doing mathematical computations on High Dimensional Data. 
* It provides inbuilt utilities which are Mutable in Nature.
* As mentiond above it is using C internally, so it is Fast in nature when it 
   compared to General Purpose Library using list available in Python.
 
## Array creation routines:
Arrays in numpy can be created in multiple ways. Let's see them one by one. <br/>
Array creation routines:
* Using Empty.
* Using Eye.
* Using One init.
* Using Zero init.
* From default value initialization(Full init)
* Using Range.
* Using Linspace
* Using Random.


* Import Numpy Library as np using below statement.

In [1]:
import numpy as np

### Using Empty:
#### empty:
* Returns a new array of given shape and type, without initializing/arbitrary entries.

In [2]:
np.empty(shape=(2, 2))

array([[  1.01937281e-311,   1.01935439e-311],
       [  1.01935438e-311,   1.01935439e-311]])

* Created array with shape (2,2). 
* Values in array are arbitrary.
* Providing dtype information along with shape.

In [5]:
np.empty(shape=(2, 2), dtype=int)

array([[ 175338341,  538976266],
       [ 623933984, 1868832882]])

#### empty_like:
* Return a new array with the same shape and type as a given array.

In [7]:
a = ([1,2,3], [4,5,6]) 

In [8]:
np.empty_like(a)

array([[ 7143497,  6750305,  2097253],
       [ 6357072,  6815860, 40239104]])

* we got the new array empty_array_copy with size of (a) but contents are arbitrary.

### Using Eye:
#### eye:
* Return a 2-D array with ones on the diagonal and zeros elsewhere.
* Creating a array and setting diagonals elements are initialized to 1.

In [10]:
np.eye(N=3,M=2,k=0,dtype=int)

array([[1, 0],
       [0, 1],
       [0, 0]])

* Here, <br />
N = Number of rows <br />
M = Nuber of columns <br />
k = Index of the diagonal(positive value refers to an upper diagonal, and a negative value to a lower diagonal.)

In [12]:
np.eye(N=3,k=-1)

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

* Since k=-1 lower diagonal elements are initialized to 1

### Using One Init:
#### ones:
* Initializes all values in array to 1.
* Creating array with 5 elements.

In [14]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

* Creating nd array.

In [15]:
np.ones(shape=(2,2,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

#### ones_like:
* creates new data structure with same dimension/size.
* Creating new array using shape of existing array.

In [351]:
np.ones_like(ones_array3D)

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

### Using Zero init:
#### zeros:
* Creates numpy array of given size and initialize values to zero.
* Creating array with elements 5.

In [18]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

* Creating nd array

In [19]:
np.zeros(shape=(2,2,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

#### zeros_like:
* same as mention before creates a new array with same dimention.
* Creating new array using zero_like shape of existing array.

In [22]:
zeros_array3D = np.zeros(shape=(2,2,3))

In [23]:
np.zeros_like(zeros_array3D)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

### From default value initialization(Full init):
#### full:
* It initializes all the values in array to given value.
* Creating array with given shape(6,6) and fill value(99).

In [25]:
np.full(shape=(6,6),fill_value=99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

* Creating a new array with given shape(3,2) and fill value 'hello'.

In [26]:
np.full(shape=(3,2),fill_value='hello')

array([['hello', 'hello'],
       ['hello', 'hello'],
       ['hello', 'hello']],
      dtype='<U5')

#### full_like:
* creates new array with shape of given array and fill value.

In [30]:
array_d = np.full(shape=(3,2),fill_value='hello')

* Creating a new array using given array size and initializes values to given fill value hello.

In [31]:
np.full_like(array_d,'hello')

array([['hello', 'hello'],
       ['hello', 'hello'],
       ['hello', 'hello']],
      dtype='<U5')

* Just remember we need to pass both array and fill_value to full_like function.

### Using Range:
* It returns evenly spaced values within the given interval.
* Creating a array with values between given start(10) and stop(20)(excludes) with given step size(2).

In [32]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

* In above Example params are (start=10,stop=20,step=2)
* Here, we can see that it included start value(10) but excluded stop value 20 and returned values with step size 2.
* So, remember it always generates values within the half-open interval [start, stop).
* Creating a array with values between given start(15) and stop(10)(excludes) with given step size(-1).

In [33]:
np.arange(15,10,-1)

array([15, 14, 13, 12, 11])

* arange function also works with negative and non-integer(eg:0.1) step size.
* But for non-integer the results will often not be consistent.
* It is better to use linspace for non integer step cases.

### Using Linspace: 
* It is also returns evenly spaced values  withing given interval like range function.
* But unlike range function it includes both start and stop values by default(eg: [start,stop]).
* optionally we can exclude stop value from interval(eg: [start,stop)).
* Creating array which size equal to given num value(5) and places values between start(2.0) and stop(3.0).

In [34]:
np.linspace(2.0, 3.0, num=5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

* Here, linspace returned 5 evenly spaced values within interval [start=2.0,stop=3.0].
* Creating array which size equal to given num value(5) and places values between start(2.0) and stop(3.0)(excludes).

In [35]:
np.linspace(2.0,3.0,num=5,endpoint=False)

array([ 2. ,  2.2,  2.4,  2.6,  2.8])

* If the endpoint is False it returns values within interval [start=2.0,stop=3.0).

### Using Random:
#### rand:
* Populates random values within interval [0,1).
* In statistical terms it returns random samples from a uniform distribution over [0, 1).
* Creating array with size equal to given integer and initializes values to random values between [0,1).


In [37]:
np.random.rand(10)

array([ 0.6139972 ,  0.25799876,  0.8001711 ,  0.21772692,  0.98987599,
        0.57680313,  0.75732044,  0.49872647,  0.12664304,  0.71950526])

* Creating array of given size and initialize values to random values between[0,1).

In [38]:
np.random.rand(3,2)

array([[ 0.37478057,  0.98476286],
       [ 0.5634953 ,  0.62533538],
       [ 0.5583982 ,  0.11736292]])

#### randn:
* It fills sample values from the “standard normal” distribution.
* standard normal distribution means mean is equal to 0 and variance is equal to 1.
* Creating array and initializing it with values in standard normal distribution.

In [39]:
np.random.randn(2,4)

array([[ 0.18582399,  0.73195491, -0.45365133,  0.50188784],
       [ 1.32856637, -1.32800226, -1.67926863, -0.73946132]])

* randn function returns a single float randomly sampled from the distribution is returned if no argument is provided.
* see the example below.

In [40]:
np.random.randn()

0.6761995548129693

#### randint:
* randint return random integers from low (inclusive) to high (exclusive).
* size and  high value is optional.
* in statistical terms return random integers from the “discrete uniform” distribution.
* Creating array with given size (3,3) and values are initialized to random values between low(5) and high(10).

In [42]:
np.random.randint(low=5,high=10,size=(3,3))

array([[9, 6, 5],
       [6, 8, 9],
       [7, 5, 9]])

* Returning an integer less than given low(5) value.

In [45]:
np.random.randint(low=5)

4

* Creating an array with given size(10) and values are initialized to random values less than low(5) value.

In [49]:
np.random.randint(low=5,size=10)

array([2, 0, 3, 3, 3, 3, 2, 3, 3, 4])

#### shuffle
* Modify a sequence in-place by shuffling its contents.
* This function only shuffles the array along the first axis of a multi-dimensional array.
* The order of sub-arrays is changed but their contents remains the same.
* Creating array and shuffle elements internally.

In [86]:
a = np.arange(10)

In [87]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.random.shuffle(a)

In [92]:
a

array([4, 5, 2, 9, 6, 7, 3, 0, 8, 1])

* Note: np.random.shuffle() returns nothing(None).
* If the data is multi dimensional array, it only shuffles along the first axis.

In [99]:
b = np.arange(9).reshape((3, 3))

In [100]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
np.random.shuffle(b)

In [103]:
b

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

* Now, check shuffle just shuffled rows(i) but not column(j) values.

#### seed:
* Seed the generator.
* It makes the random numbers predictable. Precisely, generage same output using same seed(output).
* To change the data we can re-seed the generator.
* It is very useful method when your debugging data having random calls.

In [113]:
np.random.randint(5,10,size=(3,3))

array([[5, 8, 6],
       [6, 8, 9],
       [5, 6, 8]])

In [115]:
np.random.randint(5,10,size=(3,3))

array([[6, 7, 7],
       [6, 5, 6],
       [8, 9, 8]])

* In each run data is getting varied.

In [107]:
np.random.seed(1)

* seed is initialized to 1.

In [110]:
np.random.randint(5,10,size=(3,3))

array([[9, 6, 7],
       [9, 7, 9],
       [8, 9, 7]])

In [117]:
np.random.randint(5,10,size=(3,3))

array([[6, 8, 5],
       [5, 7, 7],
       [6, 8, 9]])

* Now we can see that random data is not changing.