# Numpy Creation From Existing Data:

In [6]:
import numpy as np

### From List and Tuple:
* np.array and np.asarray functions uses existing list/tuple data to create new arrays.
#### array:<br/>
* Creates array from given list/tuple.
* Creating array by passing list as argument.

In [4]:
list_a = [2,3,4,4,5,1]

In [8]:
np.array(list_a)

array([2, 3, 4, 4, 5, 1])

* Creating array by passing tuple as argument.

In [10]:
tuple_a = (2,3,4,4,5,1)

In [11]:
np.array(tuple_a)

array([2, 3, 4, 4, 5, 1])

* We can see that in above example np.array has taken list and tuple data as input and converted them to array.
* Here, data type of array is int32.
* Using numpy we can configure dtype to another dtype as well.
* providing dtype information along with list data.

In [13]:
np.array(list_a,dtype=np.float16)

array([ 2.,  3.,  4.,  4.,  5.,  1.], dtype=float16)

* providing dtype information along with tuple data as arguments.

In [14]:
np.array(tuple_a,dtype=np.float16)

array([ 2.,  3.,  4.,  4.,  5.,  1.], dtype=float16)

* Let's see an one more example with string data.
* providing list of strings to np.array as an argument.

In [16]:
np.array(['hello','world','friends'])

array(['hello', 'world', 'friends'],
      dtype='<U7')

* providing tuple of strings to np.array

In [17]:
np.array(('hello','world','friends'))

array(['hello', 'world', 'friends'],
      dtype='<U7')

* Here,size of each element is decided by the maximum size of word.
* Here that is 7(no. of chars in friends = 7)

#### asarray:
* Creates array from list/tuple.
* works same as np.array but has fewer parameters than np.array.
* Providing list as an argument to asarray function.

In [19]:
np.asarray(a=list_a,dtype=int)

array([2, 3, 4, 4, 5, 1])

* creating array from tuple by passing as parameter.

In [20]:
np.asarray(a=tuple_a,dtype=int)

array([2, 3, 4, 4, 5, 1])

### From file:
* Load data from a text file.
* Handles missing values.
* Creating array by fasing filename/path as parameter.

In [21]:
np.genfromtxt(fname='example.txt',dtype='U16')

array('1,2,3,4,5,6',
      dtype='<U16')

* here fname can be file, str, pathlib.Path, list of str, generator.