# Numpy Creation From Existing Data:

In [58]:
import numpy as np

### From List and Tuple:
* np.array and np.asarray functions uses existing list/tuple data to create new arrays.
#### array:
* Creates array from given list/tuple.

In [81]:
# create a list 
list_a = [2,3,4,4,5,1]

In [82]:
# passing list object to np.array
np.array(list_a)

array([2, 3, 4, 4, 5, 1])

In [83]:
#creating tuple
tuple_a = (2,3,4,4,5,1)

In [84]:
# passing tuple object to np.array
np.array(tuple_a)

array([2, 3, 4, 4, 5, 1])

* We can see that in above example np.array has taken list/tuple data as input and converted them to array.
* Here, data type of array is int32.
* Using numpy we can configure dtype to another dtype as well.

In [85]:
#providing dtype information along with list data
np.array(list_a,dtype=np.float16)

array([ 2.,  3.,  4.,  4.,  5.,  1.], dtype=float16)

In [87]:
#providing dtype information along with tuple data
np.array(tuple_a,dtype=np.float16)

array([ 2.,  3.,  4.,  4.,  5.,  1.], dtype=float16)

* Let's see an one more example with string data.

In [89]:
#providing list of strings to np.array
np.array(['hello','world','friends'])

array(['hello', 'world', 'friends'],
      dtype='<U7')

In [91]:
#providing tuple of strings to np.array
np.array(('hello','world','friends'))

array(['hello', 'world', 'friends'],
      dtype='<U7')

* Here,size of each element is decided by the maximum size of word.
* Here that is 7(no. of chars in friends = 7)

#### asarray:
* Creates array from list/tuple.
* works same as np.array but has fewer parameters than np.array.

In [95]:
#creates array from list
np.asarray(a=list_a,dtype=int)

array([2, 3, 4, 4, 5, 1])

In [96]:
#creates array from list
np.asarray(a=tuple_a,dtype=int)

array([2, 3, 4, 4, 5, 1])

### From file:
* Load data from a text file.
* Handles missing values.

In [94]:
# treates array using contents in file
np.genfromtxt(fname='example.txt',dtype='U16')

array('1,2,3,4,5,6',
      dtype='<U16')

* here fname can be file, str, pathlib.Path, list of str, generator.